with open('aoc4.txt', 'r') as file:
    lines = file.read().split('\n')

sum = 0

for line in lines:
    n = 0

    # Get arrays of winning cards and the cards you own
    winning_cards = line.split('|')[0].split(":")[1].split(" ")
    cards = line.split('|')[1][1::].split(" ")

    for i in cards:
        # Ignore the ''s generated by single digit numbers
        if i != '' and i in winning_cards:
            n+=1
    
    # If n = 0, sum = 0 for that line because there are no winning cards
    if n!=0: 
        sum += pow(2, n-1)

print(sum)